stories/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', include("story9.urls")),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
]

story9/urls.py
from django.urls import path
from django.conf.urls import url
from .views import signup

app_name = 'story9'

urlpatterns = [
    path('signup/',signup, name='signup'),
]

story9/models.py
from django.db import models

# Create your models here.

story9/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

story9/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from .forms import SignUpForm

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

story9/templates/base.html
<!DOCTYPE html>

<head>
  <meta charset="utf-8">
  <title>{% block title %} Ini judul {% endblock %}</title>
</head>

<body>
  <main>
    {% block content %}

    {% endblock %}
  </main>
</body>

story9/templates/home.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% block title %} Home {% endblock %}

{% block content %}

{% if user.is_authenticated %}
  <h2> Halo, {{ user.username }}! </h2>
  <p><a href="{% url 'logout' %}">Log Out</a></p>

{% else %}
  <h2> Selamat datang di website Story 9! </h2>
  <a href="{% url 'login' %}">Log In</a>
  <a href="{% url 'story9:signup' %}">Sign Up</a>

{% endif %}

{% endblock %}

story9/templates/signup.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% block content %}

  <h2>Sign up</h2>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
  
{% endblock %}